#cloud-config

package_update: true
package_upgrade: true

write_files:
  - path: /etc/ssh/sshd_config.d/99-hardening.conf
    content: |
      PasswordAuthentication no
      PermitRootLogin no
      X11Forwarding no
    owner: root:root
    permissions: '0644'

runcmd:
  - systemctl restart sshd
  - firewall-offline-cmd --zone=public --add-service=ssh
  - firewall-offline-cmd --zone=public --remove-service=dhcpv6-client || true
  - systemctl enable --now firewalld